In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [2]:
# Numpy's main datatyoe is ndarray

a1 = np.array([1,2,3])

In [3]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3.3],
                [4,5,6.2]])
a3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

In [9]:
type(a2)

numpy.ndarray

In [8]:
type(a3)

numpy.ndarray

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [22]:
# Create a DataFrame from a Numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.2

## 2. Creating Arrays

In [37]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [38]:
sample_array.dtype

dtype('int32')

In [43]:
ones = np.ones((10,10))

In [44]:
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
ones.dtype

dtype('float64')

In [46]:
type(ones)

numpy.ndarray

In [47]:
zeros = np.zeros((10,10))

In [48]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
zeros.dtype

dtype('float64')

In [50]:
type(zeros)

numpy.ndarray

In [51]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [54]:
random_array = np.random.randint(10, 21, size=(10,10))

In [55]:
random_array

array([[15, 14, 17, 17, 12, 13, 19, 11, 17, 11],
       [12, 17, 20, 14, 18, 14, 20, 19, 18, 17],
       [20, 10, 10, 16, 15, 11, 12, 13, 19, 13],
       [10, 17, 13, 20, 12, 17, 10, 17, 19, 10],
       [17, 12, 18, 12, 11, 20, 16, 10, 10, 10],
       [10, 15, 11, 11, 18, 18, 13, 10, 13, 19],
       [17, 19, 13, 17, 15, 13, 20, 12, 19, 17],
       [15, 14, 13, 16, 10, 10, 13, 10, 11, 19],
       [20, 19, 16, 15, 16, 15, 13, 17, 15, 19],
       [20, 14, 11, 10, 20, 18, 11, 18, 13, 10]])

In [56]:
random_array.shape

(10, 10)

In [57]:
random_array_2 = np.random.random((5,3))

In [58]:
random_array_2

array([[0.08332046, 0.82591475, 0.0442877 ],
       [0.84456734, 0.0379645 , 0.89556566],
       [0.71239762, 0.96418771, 0.10508636],
       [0.88646374, 0.65198755, 0.90977448],
       [0.94278401, 0.84312017, 0.4531927 ]])

In [59]:
random_array_2.shape

(5, 3)

In [62]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.84867593, 0.51951517, 0.15968863],
       [0.82181062, 0.18634179, 0.69671471],
       [0.96312069, 0.23734551, 0.75303291],
       [0.97527312, 0.46505235, 0.23325242],
       [0.72625272, 0.54416841, 0.12038434]])